version: '2'
services:
    reservationapp-app:
        image: reservationapp
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://reservationapp-postgresql:5432/ReservationApp
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    reservationapp-postgresql:
        extends:
            file: postgresql.yml
            service: reservationapp-postgresql
