version: '2'
services:
    reservationapp-postgresql:
        image: postgres:9.6.5
        # volumes:
        #     - ~/volumes/jhipster/ReservationApp/postgresql/:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=ReservationApp
            - POSTGRES_PASSWORD=
        ports:
            - 5432:5432
